//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;

namespace DavinSys.StockReader.Data {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StockReaderInfo {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ColumnList", typeof(StockReaderInfoColumnList), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ConfigData", typeof(StockReaderInfoConfigData), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("TickerList", typeof(StockReaderInfoTickerList), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
		[XmlIgnore]
		public List<string> Tickers
		{
			get
			{
				StringBuilder sb = new StringBuilder();
				List<string> list = new List<string>();

				StockReaderInfoTickerList tickerList = (StockReaderInfoTickerList)Items[1];

				foreach (StockReaderInfoTickerListTicker ticker in tickerList.Ticker)
				{
					list.Add(ticker.Value);
				}

				return list;
			}

			set
			{
				int idx = 0;
				StockReaderInfoTickerList list = new StockReaderInfoTickerList();
				StockReaderInfoTickerListTicker item;

				list.Ticker = new StockReaderInfoTickerListTicker[value.Count];
				foreach (string ticker in value)
				{
					item = new StockReaderInfoTickerListTicker();
					item.Value = ticker;
					list.Ticker.SetValue(item, idx++);
				}

				Items[2] = list;
			}
		}

		[XmlIgnore]
		public int TimerInterval
		{
			get
			{
				StockReaderInfoConfigData data = (StockReaderInfoConfigData)Items[0];
				int val;

				if (int.TryParse(data.Timer[0].interval, out val) == true)
				{
					return val;
				}
				else
				{
					return -1;
				}
			}

			set
			{
				StockReaderInfoConfigData data = (StockReaderInfoConfigData)Items[0];
				data.Timer[0].interval = value.ToString();
			}
		}

		[XmlIgnore]
		public List<StockReaderInfoColumnListColumnDef> Columns
		{
			get
			{
				List<StockReaderInfoColumnListColumnDef> list = new List<StockReaderInfoColumnListColumnDef>();

				StockReaderInfoColumnList colList = (StockReaderInfoColumnList)Items[2];

				foreach (StockReaderInfoColumnListColumnDef def in colList.ColumnDef)
				{
					def.Selected = true;
					list.Add(def);
				}

				return list;
			}
		}

	}
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StockReaderInfoColumnList 
	{
        
        private StockReaderInfoColumnListColumnDef[] columnDefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ColumnDef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockReaderInfoColumnListColumnDef[] ColumnDef {
            get {
                return this.columnDefField;
            }
            set {
                this.columnDefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class StockReaderInfoColumnListColumnDef
	{
        
        private string colNameField;
        
        private string bindingColumnField;
        
        private string colHeadingField;
        
        private string colFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColName {
            get {
                return this.colNameField;
            }
            set {
                this.colNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BindingColumn {
            get {
                return this.bindingColumnField;
            }
            set {
                this.bindingColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColHeading {
            get {
                return this.colHeadingField;
            }
            set {
                this.colHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ColFormat {
            get {
                return this.colFormatField;
            }
            set {
                this.colFormatField = value;
            }
        }

		[XmlIgnore]
		public bool Selected;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StockReaderInfoConfigData {
        
        private StockReaderInfoConfigDataTimer[] timerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Timer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockReaderInfoConfigDataTimer[] Timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StockReaderInfoConfigDataTimer {
        
        private string intervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StockReaderInfoTickerList {
        
        private StockReaderInfoTickerListTicker[] tickerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ticker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public StockReaderInfoTickerListTicker[] Ticker {
            get {
                return this.tickerField;
            }
            set {
                this.tickerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StockReaderInfoTickerListTicker {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
